In [1]:
import pandas as pd
import os
import json

In [2]:
matches_l = []

In [3]:
for file_name in os.listdir('./processed_data/matches/'):
    if not os.path.isfile(os.path.join('./processed_data/matches/', file_name)):
        print(file_name, "not a file")
        continue
    with open(os.path.join('./processed_data/matches/', file_name)) as f:
        try:
            s = json.load(f)
            matches_l.append(s)
        except UnicodeDecodeError:
            print(file_name)

.ipynb_checkpoints not a file

In [4]:
matches = pd.DataFrame.from_records(matches_l)

In [5]:
matches.head()

,city,date,dl_applied,eliminator,id,overs,player_of_match,result,season,team1,team2,toss_decision,toss_winner,umpire1,umpire2,umpire3,venue,win_by_runs,win_by_wickets,winner
0,Dharamsala,2012-05-19,,,548374,20,UT Yadav,,2012,Kings XI Punjab,Delhi Daredevils,field,Delhi Daredevils,BF Bowden,VA Kulkarni,,Himachal Pradesh Cricket Association Stadium,,6,Delhi Daredevils
1,Jaipur,2008-05-26,,,336036,20,Sohail Tanvir,,2008,Rajasthan Royals,Mumbai Indians,field,Rajasthan Royals,BF Bowden,K Hariharan,,Sawai Mansingh Stadium,,5,Rajasthan Royals
2,,2014-04-19,,,729289,20,JP Duminy,,2014,Kolkata Knight Riders,Delhi Daredevils,bat,Kolkata Knight Riders,Aleem Dar,VA Kulkarni,,Dubai International Cricket Stadium,,4,Delhi Daredevils
3,Centurion,2009-04-30,,,392201,20,DP Nannes,,2009,Deccan Chargers,Delhi Daredevils,field,Delhi Daredevils,GAV Baxter,AM Saheba,,SuperSport Park,,6,Delhi Daredevils
4,Mumbai,2010-03-28,,,419130,20,Harbhajan Singh,,2010,Deccan Chargers,Mumbai Indians,field,Deccan Chargers,S Das,K Hariharan,,Dr DY Patil Sports Academy,41,,Mumbai Indians

In [6]:
matches.to_csv('matches.csv', index=False)

In [7]:
balls_l = []

In [8]:
def process_innings_dict(inning_info: dict, match_id: str, match_inning: str):
    balls_list = []
    for ball_info in inning_info:
        for key, value in ball_info.items():
            inning, ball = key.split(".")
            runs = value.pop("runs")
            value.update(match_id=match_id, inning=inning, ball=ball, 
                         match_inning=match_inning, runs_batsman=runs["batsman"], 
                         runs_extras=runs["extras"], runs_total=runs["total"])
            balls_list.append(value)
    return balls_list

In [9]:
for file_name in os.listdir("./processed_data/innings/"):
    if not os.path.isfile(os.path.join('./processed_data/innings/', file_name)):
        print(file_name, "not a file")
        continue
    with open(os.path.join('./processed_data/innings/', file_name)) as f:
        try:
            inning_info = json.load(f)
            match_id = file_name.split("_")[0]
            match_inning = file_name.split("_")[1]
            balls_list = process_innings_dict(inning_info, match_id, match_inning)
            balls_l.extend(balls_list)
        except json.JSONDecodeError:
            print(file_name)

829763_2nd_inn.json
501265_2nd_inn.json
.ipynb_checkpoints not a file

In [10]:
balls = pd.DataFrame(balls_l)

In [11]:
balls.head()

,ball,batsman,bowler,extras,inning,match_id,match_inning,non_striker,replacements,runs_batsman,runs_extras,runs_total,wicket
0,1,SP Narine,K Gowtham,NaN,0,1136575,2nd,CA Lynn,NaN,1,0,1,NaN
1,2,CA Lynn,K Gowtham,NaN,0,1136575,2nd,SP Narine,NaN,0,0,0,NaN
2,3,CA Lynn,K Gowtham,NaN,0,1136575,2nd,SP Narine,NaN,0,0,0,"{'player_out': 'CA Lynn', 'kind': 'bowled'}"
3,4,RV Uthappa,K Gowtham,NaN,0,1136575,2nd,SP Narine,NaN,0,0,0,NaN
4,5,RV Uthappa,K Gowtham,NaN,0,1136575,2nd,SP Narine,NaN,0,0,0,NaN

In [12]:
balls.to_csv("balls.csv", index=False)